version: '3'
services:
  oracle-db:
    image: 'luisaxsz/oracle-xe-18.4.0:18.4.0'
    container_name: oracle-xe-18.4.0
    restart: always
    environment:
        - ORACLE_ALLOW_REMOTE=true
        - ORACLE_DISABLE_ASYNCH_IO=true
        - ORACLE_SID=XE
    volumes:
      - ./src/main/resources/db:/opt/oracle/scripts/startup
    ports:
      - '1521:1521'
  keycloak:
    image: 'quay.io/keycloak/keycloak:25.0.2'
    container_name: my-keycloak
    environment:
      KC_HOSTNAME: localhost
      KC_PORT: 8085
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-mem
    command:
      ['start-dev', '--http-port=8085']
    ports:
      - 8085:8085
