CONNECT SYSTEM/oracle@XE
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE TABLESPACE CONTROLEGASTOS DATAFILE '/opt/oracle/oradata/CONTROLEGASTOS01.dbf' SIZE 100M ONLINE;
CREATE TABLESPACE idx_CONTROLEGASTOS DATAFILE '/opt/oracle/oradata/idx_CONTROLEGASTOS01.dbf' SIZE 100M;
CREATE USER CONTROLEGASTOS IDENTIFIED BY CONTROLEGASTOS DEFAULT TABLESPACE CONTROLEGASTOS TEMPORARY TABLESPACE TEMP;
ALTER USER CONTROLEGASTOS QUOTA UNLIMITED ON CONTROLEGASTOS;
GRANT CONNECT TO CONTROLEGASTOS;
GRANT RESOURCE TO CONTROLEGASTOS;
GRANT CREATE VIEW TO CONTROLEGASTOS;
GRANT CREATE PROCEDURE TO CONTROLEGASTOS;
GRANT CREATE JOB TO CONTROLEGASTOS;
ALTER USER CONTROLEGASTOS DEFAULT ROLE CONNECT, RESOURCE;
COMMIT;
EXIT;
